"""Generate the site pages that mirror files kept elsewhere in the repo.

Two pages on the documentation site show content whose home is somewhere else:

    README.md, from "## What surprised me" onwards  ->  docs/tradeoffs.md
    NOTES.md                                        ->  docs/build-log.md

The exercise asks for the write-up to live in the README, so it stays there and
this copies it onto the site rather than moving it. Generating the copy instead
of maintaining one by hand is the whole point: two hand-kept copies of the same
paragraphs drift, and docs/contracts.md already drifted from the code once by
saying 2KB per patch where the config says 1,500 characters.

Run it with `task docs:sync` after editing the README write-up or NOTES.md.
Nothing here edits the source files.
"""

from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

GENERATED = "<!-- GENERATED by scripts/sync_docs.py. Edit the source, then run `task docs:sync`. -->"


def write_page(target: pathlib.Path, front_matter: str, intro: str, body: str) -> bool:
    new = f"{front_matter}\n{GENERATED}\n\n{intro}\n\n{body.rstrip()}\n"
    old = target.read_text() if target.exists() else ""
    if old == new:
        return False
    target.write_text(new)
    return True


def tradeoffs() -> bool:
    """The four write-up sections, verbatim from the README."""
    readme = (ROOT / "README.md").read_text()
    marker = "## What surprised me"
    if marker not in readme:
        sys.exit(f"sync_docs: '{marker}' not found in README.md")

    body = readme[readme.index(marker):]

    front = (
        "---\n"
        "title: Tradeoffs\n"
        "layout: default\n"
        "nav_order: 2\n"
        "---\n"
    )
    intro = (
        "What I found surprising, the decisions I made and would reverse, where this\n"
        "falls over in production, and who it is actually for.\n\n"
        "This is the same text as the bottom of the\n"
        "[README](https://github.com/pablogd-hashi/rp-ghtriage#readme), which is where it\n"
        "lives. It is reproduced here so it is readable without scrolling through the run\n"
        "instructions first."
    )
    return write_page(ROOT / "docs/tradeoffs.md", front, intro, body)


def build_log() -> bool:
    """NOTES.md, the running log of what broke."""
    notes = (ROOT / "NOTES.md").read_text()

    # Drop the H1 and the explanatory preamble; the page front matter replaces them.
    marker = "---\n"
    body = notes.split(marker, 1)[1] if marker in notes else notes

    front = (
        "---\n"
        "title: Build log\n"
        "layout: default\n"
        "nav_order: 7\n"
        "---\n"
    )
    intro = (
        "# Build log\n\n"
        "Two lines per breakage: what I expected, and what actually happened. Written as I\n"
        "went rather than tidied up afterwards, which is the only reason it is worth\n"
        "reading.\n\n"
        "Source: [NOTES.md](https://github.com/pablogd-hashi/rp-ghtriage/blob/main/NOTES.md)."
    )
    return write_page(ROOT / "docs/build-log.md", front, intro, body)


def main() -> int:
    changed = [name for name, fn in (("docs/tradeoffs.md", tradeoffs),
                                     ("docs/build-log.md", build_log)) if fn()]
    if changed:
        print("regenerated: " + ", ".join(changed))
    else:
        print("already up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
