"""Generate the site pages that mirror files kept elsewhere in the repo.

Two pages on the documentation site show content whose home is somewhere else:

    README.md, from "## What surprised me" onwards  ->  docs/tradeoffs.md

The exercise asks for the write-up to live in the README, so it stays there and
this copies it onto the site rather than moving it. Generating the copy instead
of maintaining one by hand is the whole point: two hand-kept copies of the same
paragraphs drift, and docs/contracts.md already drifted from the code once by
saying 2KB per patch where the config says 1,500 characters.

Run it with `task docs:sync` after editing the README write-up.
Nothing here edits the source files.
"""

from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

GENERATED = "<!-- GENERATED by scripts/sync_docs.py. Edit the source, then run `task docs:sync`. -->"


def write_page(target: pathlib.Path, front_matter: str, intro: str, body: str) -> bool:
    new = f"{front_matter}\n{GENERATED}\n\n{intro}\n\n{body.rstrip()}\n"
    old = target.read_text() if target.exists() else ""
    if old == new:
        return False
    target.write_text(new)
    return True


def tradeoffs() -> bool:
    """The four write-up sections, verbatim from the README."""
    readme = (ROOT / "README.md").read_text()
    marker = "## What surprised me"
    if marker not in readme:
        sys.exit(f"sync_docs: '{marker}' not found in README.md")

    body = readme[readme.index(marker):]

    front = (
        "---\n"
        "title: Tradeoffs\n"
        "layout: default\n"
        "nav_order: 6\n"
        "---\n"
    )
    # No preamble. The sections speak for themselves and an interviewer opening this
    # page does not need to be told what a tradeoff is.
    return write_page(ROOT / "docs/tradeoffs.md", front, "", body)


def main() -> int:
    changed = [name for name, fn in (("docs/tradeoffs.md", tradeoffs),) if fn()]
    if changed:
        print("regenerated: " + ", ".join(changed))
    else:
        print("already up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
