apiVersion: 1
datasources:
  - name: Prometheus
    uid: prom
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
  - name: Postgres
    uid: pg
    type: postgres
    url: postgres:5432
    user: triage
    database: triage
    secureJsonData:
      password: triage
    jsonData:
      sslmode: disable
      postgresVersion: 1600
